// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gps_translation_hls_get_field_from_nmea (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fieldnum,
        stored_msg_address0,
        stored_msg_ce0,
        stored_msg_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] fieldnum;
output  [6:0] stored_msg_address0;
output   stored_msg_ce0;
input  [7:0] stored_msg_q0;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] select_ln51_fu_58_p3;
reg   [3:0] select_ln51_reg_136;
wire   [6:0] trunc_ln51_fu_82_p1;
reg   [6:0] trunc_ln51_reg_144;
wire    ap_CS_fsm_state2;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_done;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_idle;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_ready;
wire   [63:0] grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out_ap_vld;
wire   [6:0] grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_address0;
wire    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_ce0;
reg    grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg;
wire   [0:0] icmp_ln51_1_fu_87_p2;
wire    ap_CS_fsm_state3;
reg   [63:0] add_ln51_loc_fu_34;
reg   [63:0] idx2_fu_26;
wire   [63:0] add_ln57_fu_106_p2;
wire    ap_CS_fsm_state4;
reg   [3:0] i_fu_30;
wire   [3:0] i_2_fu_92_p2;
wire   [0:0] icmp_ln51_fu_52_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg = 1'b0;
#0 idx2_fu_26 = 64'd0;
#0 i_fu_30 = 4'd0;
end

gps_translation_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2 grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start),
    .ap_done(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_done),
    .ap_idle(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_idle),
    .ap_ready(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_ready),
    .empty(trunc_ln51_reg_144),
    .add_ln51_out(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out),
    .add_ln51_out_ap_vld(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out_ap_vld),
    .stored_msg_address0(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_address0),
    .stored_msg_ce0(grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln51_1_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_ready == 1'b1)) begin
            grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_30 <= 4'd0;
    end else if (((icmp_ln51_1_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_30 <= i_2_fu_92_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        idx2_fu_26 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        idx2_fu_26 <= add_ln57_fu_106_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln51_loc_fu_34 <= grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_add_ln51_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln51_reg_136 <= select_ln51_fu_58_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln51_reg_144 <= trunc_ln51_fu_82_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln51_1_fu_87_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_1_fu_87_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln51_1_fu_87_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_fu_106_p2 = (add_ln51_loc_fu_34 + idx2_fu_26);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return = idx2_fu_26[6:0];

assign grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start = grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_ap_start_reg;

assign i_2_fu_92_p2 = (i_fu_30 + 4'd1);

assign icmp_ln51_1_fu_87_p2 = ((i_fu_30 == select_ln51_reg_136) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_52_p2 = ((fieldnum != 4'd0) ? 1'b1 : 1'b0);

assign select_ln51_fu_58_p3 = ((icmp_ln51_fu_52_p2[0:0] == 1'b1) ? fieldnum : 4'd1);

assign stored_msg_address0 = grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_address0;

assign stored_msg_ce0 = grp_hls_get_field_from_nmea_Pipeline_VITIS_LOOP_53_2_fu_44_stored_msg_ce0;

assign trunc_ln51_fu_82_p1 = idx2_fu_26[6:0];

endmodule //gps_translation_hls_get_field_from_nmea
