// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gps_translation_hls_atoi_w_len (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s,
        n,
        stored_msg_address0,
        stored_msg_ce0,
        stored_msg_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] s;
input  [2:0] n;
output  [6:0] stored_msg_address0;
output   stored_msg_ce0;
input  [7:0] stored_msg_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_done;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_idle;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_ready;
wire   [31:0] grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out_ap_vld;
wire   [0:0] grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_is_neg_out;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_is_neg_out_ap_vld;
wire   [6:0] grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_address0;
wire    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_ce0;
reg    grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] sub_ln16_fu_54_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg = 1'b0;
end

gps_translation_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1 grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start),
    .ap_done(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_done),
    .ap_idle(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_idle),
    .ap_ready(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_ready),
    .s(s),
    .n(n),
    .res_out(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out),
    .res_out_ap_vld(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out_ap_vld),
    .is_neg_out(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_is_neg_out),
    .is_neg_out_ap_vld(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_is_neg_out_ap_vld),
    .stored_msg_address0(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_address0),
    .stored_msg_ce0(grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg <= 1'b1;
        end else if ((grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_ready == 1'b1)) begin
            grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return = ((grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_is_neg_out[0:0] == 1'b1) ? sub_ln16_fu_54_p2 : grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out);

assign grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start = grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_ap_start_reg;

assign stored_msg_address0 = grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_address0;

assign stored_msg_ce0 = grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_stored_msg_ce0;

assign sub_ln16_fu_54_p2 = (32'd0 - grp_hls_atoi_w_len_Pipeline_VITIS_LOOP_8_1_fu_36_res_out);

endmodule //gps_translation_hls_atoi_w_len
