// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gps_translation_hls_get_coordinate_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stored_msg_address0,
        stored_msg_ce0,
        stored_msg_q0,
        ap_return,
        grp_fu_792_p_din0,
        grp_fu_792_p_din1,
        grp_fu_792_p_opcode,
        grp_fu_792_p_dout0,
        grp_fu_792_p_ce,
        grp_fu_796_p_din0,
        grp_fu_796_p_din1,
        grp_fu_796_p_dout0,
        grp_fu_796_p_ce,
        grp_fu_800_p_din0,
        grp_fu_800_p_dout0,
        grp_fu_800_p_ce
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] stored_msg_address0;
output   stored_msg_ce0;
input  [7:0] stored_msg_q0;
output  [31:0] ap_return;
output  [31:0] grp_fu_792_p_din0;
output  [31:0] grp_fu_792_p_din1;
output  [1:0] grp_fu_792_p_opcode;
input  [31:0] grp_fu_792_p_dout0;
output   grp_fu_792_p_ce;
output  [31:0] grp_fu_796_p_din0;
output  [31:0] grp_fu_796_p_din1;
input  [31:0] grp_fu_796_p_dout0;
output   grp_fu_796_p_ce;
output  [31:0] grp_fu_800_p_din0;
input  [31:0] grp_fu_800_p_dout0;
output   grp_fu_800_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] stored_msg_address0;
reg stored_msg_ce0;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] grp_hls_get_field_from_nmea_fu_45_ap_return;
reg   [6:0] reg_84;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state18;
reg   [31:0] reg_89;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state13;
reg   [31:0] reg_95;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state17;
reg   [31:0] reg_100;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state19;
wire   [31:0] grp_hls_atoi_w_len_fu_54_ap_return;
reg   [31:0] tmp_reg_140;
wire    ap_CS_fsm_state4;
wire   [6:0] add_ln94_fu_106_p2;
reg   [6:0] add_ln94_reg_145;
wire    ap_CS_fsm_state5;
reg   [31:0] tmp_1_reg_150;
wire    ap_CS_fsm_state6;
wire   [6:0] add_ln95_fu_113_p2;
reg   [6:0] add_ln95_reg_155;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    grp_hls_get_field_from_nmea_fu_45_ap_start;
wire    grp_hls_get_field_from_nmea_fu_45_ap_done;
wire    grp_hls_get_field_from_nmea_fu_45_ap_idle;
wire    grp_hls_get_field_from_nmea_fu_45_ap_ready;
reg   [3:0] grp_hls_get_field_from_nmea_fu_45_fieldnum;
wire   [6:0] grp_hls_get_field_from_nmea_fu_45_stored_msg_address0;
wire    grp_hls_get_field_from_nmea_fu_45_stored_msg_ce0;
wire    grp_hls_atoi_w_len_fu_54_ap_start;
wire    grp_hls_atoi_w_len_fu_54_ap_done;
wire    grp_hls_atoi_w_len_fu_54_ap_idle;
wire    grp_hls_atoi_w_len_fu_54_ap_ready;
reg   [6:0] grp_hls_atoi_w_len_fu_54_s;
reg   [2:0] grp_hls_atoi_w_len_fu_54_n;
wire   [6:0] grp_hls_atoi_w_len_fu_54_stored_msg_address0;
wire    grp_hls_atoi_w_len_fu_54_stored_msg_ce0;
reg    grp_hls_get_field_from_nmea_fu_45_ap_start_reg;
reg    grp_hls_atoi_w_len_fu_54_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln69_fu_120_p1;
wire   [31:0] deg_2_fu_69_p1;
wire    ap_CS_fsm_state20;
reg   [31:0] grp_fu_73_p0;
reg   [31:0] grp_fu_73_p1;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state15;
reg   [31:0] grp_fu_79_p0;
wire   [0:0] icmp_ln99_fu_125_p2;
reg    grp_fu_65_ce;
wire   [31:0] deg_2_fu_69_p2;
reg    grp_fu_79_ce;
reg   [31:0] ap_return_preg;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_hls_get_field_from_nmea_fu_45_ap_start_reg = 1'b0;
#0 grp_hls_atoi_w_len_fu_54_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

gps_translation_hls_get_field_from_nmea grp_hls_get_field_from_nmea_fu_45(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hls_get_field_from_nmea_fu_45_ap_start),
    .ap_done(grp_hls_get_field_from_nmea_fu_45_ap_done),
    .ap_idle(grp_hls_get_field_from_nmea_fu_45_ap_idle),
    .ap_ready(grp_hls_get_field_from_nmea_fu_45_ap_ready),
    .fieldnum(grp_hls_get_field_from_nmea_fu_45_fieldnum),
    .stored_msg_address0(grp_hls_get_field_from_nmea_fu_45_stored_msg_address0),
    .stored_msg_ce0(grp_hls_get_field_from_nmea_fu_45_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_get_field_from_nmea_fu_45_ap_return)
);

gps_translation_hls_atoi_w_len grp_hls_atoi_w_len_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hls_atoi_w_len_fu_54_ap_start),
    .ap_done(grp_hls_atoi_w_len_fu_54_ap_done),
    .ap_idle(grp_hls_atoi_w_len_fu_54_ap_idle),
    .ap_ready(grp_hls_atoi_w_len_fu_54_ap_ready),
    .s(grp_hls_atoi_w_len_fu_54_s),
    .n(grp_hls_atoi_w_len_fu_54_n),
    .stored_msg_address0(grp_hls_atoi_w_len_fu_54_stored_msg_address0),
    .stored_msg_ce0(grp_hls_atoi_w_len_fu_54_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_atoi_w_len_fu_54_ap_return)
);

gps_translation_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U26(
    .din0(reg_100),
    .din1(deg_2_fu_69_p1),
    .dout(deg_2_fu_69_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            ap_return_preg <= deg_2_fu_69_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hls_atoi_w_len_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_hls_atoi_w_len_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_hls_atoi_w_len_fu_54_ap_ready == 1'b1)) begin
            grp_hls_atoi_w_len_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hls_get_field_from_nmea_fu_45_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
            grp_hls_get_field_from_nmea_fu_45_ap_start_reg <= 1'b1;
        end else if ((grp_hls_get_field_from_nmea_fu_45_ap_ready == 1'b1)) begin
            grp_hls_get_field_from_nmea_fu_45_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln94_reg_145 <= add_ln94_fu_106_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln95_reg_155 <= add_ln95_fu_113_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        reg_100 <= grp_fu_792_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_84 <= grp_hls_get_field_from_nmea_fu_45_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_89 <= grp_fu_800_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_95 <= grp_fu_796_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_1_reg_150 <= grp_hls_atoi_w_len_fu_54_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_140 <= grp_hls_atoi_w_len_fu_54_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_return = deg_2_fu_69_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state18) & (grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b1)))) begin
        grp_fu_65_ce = 1'b1;
    end else begin
        grp_fu_65_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_73_p0 = reg_100;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_73_p0 = reg_89;
    end else begin
        grp_fu_73_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_73_p1 = 32'd1114636288;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_73_p1 = 32'd1203982336;
    end else begin
        grp_fu_73_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state18) & (grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state8) & (grp_hls_atoi_w_len_fu_54_ap_done == 1'b1)))) begin
        grp_fu_79_ce = 1'b1;
    end else begin
        grp_fu_79_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_79_p0 = tmp_reg_140;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_79_p0 = tmp_1_reg_150;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_79_p0 = grp_hls_atoi_w_len_fu_54_ap_return;
    end else begin
        grp_fu_79_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_hls_atoi_w_len_fu_54_n = 3'd5;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_hls_atoi_w_len_fu_54_n = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_hls_atoi_w_len_fu_54_n = 3'd3;
    end else begin
        grp_hls_atoi_w_len_fu_54_n = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_hls_atoi_w_len_fu_54_s = add_ln95_reg_155;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_hls_atoi_w_len_fu_54_s = add_ln94_reg_145;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_hls_atoi_w_len_fu_54_s = reg_84;
    end else begin
        grp_hls_atoi_w_len_fu_54_s = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_hls_get_field_from_nmea_fu_45_fieldnum = 4'd6;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_hls_get_field_from_nmea_fu_45_fieldnum = 4'd5;
    end else begin
        grp_hls_get_field_from_nmea_fu_45_fieldnum = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        stored_msg_address0 = zext_ln69_fu_120_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        stored_msg_address0 = grp_hls_atoi_w_len_fu_54_stored_msg_address0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state2))) begin
        stored_msg_address0 = grp_hls_get_field_from_nmea_fu_45_stored_msg_address0;
    end else begin
        stored_msg_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        stored_msg_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        stored_msg_ce0 = grp_hls_atoi_w_len_fu_54_stored_msg_ce0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state2))) begin
        stored_msg_ce0 = grp_hls_get_field_from_nmea_fu_45_stored_msg_ce0;
    end else begin
        stored_msg_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_hls_atoi_w_len_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_hls_atoi_w_len_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_hls_atoi_w_len_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (grp_hls_get_field_from_nmea_fu_45_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln94_fu_106_p2 = (reg_84 + 7'd3);

assign add_ln95_fu_113_p2 = (reg_84 + 7'd6);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign deg_2_fu_69_p1 = ((icmp_ln99_fu_125_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd3212836864);

assign grp_fu_792_p_ce = grp_fu_65_ce;

assign grp_fu_792_p_din0 = grp_fu_800_p_dout0;

assign grp_fu_792_p_din1 = reg_95;

assign grp_fu_792_p_opcode = 2'd0;

assign grp_fu_796_p_ce = 1'b1;

assign grp_fu_796_p_din0 = grp_fu_73_p0;

assign grp_fu_796_p_din1 = grp_fu_73_p1;

assign grp_fu_800_p_ce = grp_fu_79_ce;

assign grp_fu_800_p_din0 = grp_fu_79_p0;

assign grp_hls_atoi_w_len_fu_54_ap_start = grp_hls_atoi_w_len_fu_54_ap_start_reg;

assign grp_hls_get_field_from_nmea_fu_45_ap_start = grp_hls_get_field_from_nmea_fu_45_ap_start_reg;

assign icmp_ln99_fu_125_p2 = ((stored_msg_q0 == 8'd69) ? 1'b1 : 1'b0);

assign zext_ln69_fu_120_p1 = reg_84;

endmodule //gps_translation_hls_get_coordinate_1
