// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gps_translation_gps_translation,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=69.927000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2480,HLS_SYN_LUT=5636,HLS_VERSION=2023_2_1}" *)

module gps_translation (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        msg_TDATA,
        msg_TVALID,
        msg_TREADY,
        pps,
        gd,
        gd_ap_vld,
        data_valid,
        data_valid_ap_vld
);

parameter    ap_ST_fsm_state1 = 29'd1;
parameter    ap_ST_fsm_state2 = 29'd2;
parameter    ap_ST_fsm_state3 = 29'd4;
parameter    ap_ST_fsm_state4 = 29'd8;
parameter    ap_ST_fsm_state5 = 29'd16;
parameter    ap_ST_fsm_state6 = 29'd32;
parameter    ap_ST_fsm_state7 = 29'd64;
parameter    ap_ST_fsm_state8 = 29'd128;
parameter    ap_ST_fsm_state9 = 29'd256;
parameter    ap_ST_fsm_state10 = 29'd512;
parameter    ap_ST_fsm_state11 = 29'd1024;
parameter    ap_ST_fsm_state12 = 29'd2048;
parameter    ap_ST_fsm_state13 = 29'd4096;
parameter    ap_ST_fsm_state14 = 29'd8192;
parameter    ap_ST_fsm_state15 = 29'd16384;
parameter    ap_ST_fsm_state16 = 29'd32768;
parameter    ap_ST_fsm_state17 = 29'd65536;
parameter    ap_ST_fsm_state18 = 29'd131072;
parameter    ap_ST_fsm_state19 = 29'd262144;
parameter    ap_ST_fsm_state20 = 29'd524288;
parameter    ap_ST_fsm_state21 = 29'd1048576;
parameter    ap_ST_fsm_state22 = 29'd2097152;
parameter    ap_ST_fsm_state23 = 29'd4194304;
parameter    ap_ST_fsm_state24 = 29'd8388608;
parameter    ap_ST_fsm_state25 = 29'd16777216;
parameter    ap_ST_fsm_state26 = 29'd33554432;
parameter    ap_ST_fsm_state27 = 29'd67108864;
parameter    ap_ST_fsm_state28 = 29'd134217728;
parameter    ap_ST_fsm_state29 = 29'd268435456;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] msg_TDATA;
input   msg_TVALID;
output   msg_TREADY;
input  [0:0] pps;
output  [319:0] gd;
output   gd_ap_vld;
output  [0:0] data_valid;
output   data_valid_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg gd_ap_vld;
reg data_valid_ap_vld;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [28:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] msg_shift_address0;
reg    msg_shift_ce0;
reg    msg_shift_we0;
reg   [7:0] msg_shift_d0;
wire   [7:0] msg_shift_q0;
reg    msg_shift_ce1;
wire   [7:0] msg_shift_q1;
reg   [6:0] stored_msg_address0;
reg    stored_msg_ce0;
reg    stored_msg_we0;
wire   [7:0] stored_msg_q0;
reg    msg_TDATA_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] pps_read_read_fu_142_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_nbreadreq_fu_148_p3;
reg   [0:0] tmp_reg_676;
wire   [0:0] icmp_ln127_fu_299_p2;
reg   [0:0] icmp_ln127_reg_680;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return;
reg   [0:0] targetBlock_reg_689;
wire    ap_CS_fsm_state7;
wire   [6:0] grp_hls_get_field_from_nmea_fu_234_ap_return;
reg   [6:0] ts_str_reg_693;
wire    ap_CS_fsm_state11;
reg   [6:0] date_str_reg_700;
wire    ap_CS_fsm_state13;
wire   [31:0] grp_hls_atoi_w_len_fu_243_ap_return;
reg   [31:0] tmp_9_reg_707;
wire    ap_CS_fsm_state15;
wire   [23:0] trunc_ln146_fu_305_p1;
reg   [23:0] trunc_ln146_reg_712;
wire   [27:0] trunc_ln146_1_fu_309_p1;
reg   [27:0] trunc_ln146_1_reg_717;
wire   [6:0] add_ln141_fu_313_p2;
reg   [6:0] add_ln141_reg_722;
wire    ap_CS_fsm_state16;
reg   [31:0] tmp_s_reg_727;
wire    ap_CS_fsm_state17;
wire   [29:0] add_ln146_fu_343_p2;
reg   [29:0] add_ln146_reg_732;
wire   [25:0] trunc_ln146_2_fu_349_p1;
reg   [25:0] trunc_ln146_2_reg_737;
wire   [6:0] add_ln142_fu_353_p2;
reg   [6:0] add_ln142_reg_742;
wire    ap_CS_fsm_state18;
reg   [31:0] tmp_1_reg_747;
wire    ap_CS_fsm_state19;
wire   [31:0] add_ln146_1_fu_379_p2;
reg   [31:0] add_ln146_1_reg_752;
reg   [31:0] d_reg_758;
wire    ap_CS_fsm_state21;
wire   [6:0] add_ln144_fu_385_p2;
reg   [6:0] add_ln144_reg_764;
wire    ap_CS_fsm_state22;
reg   [31:0] m_reg_769;
wire    ap_CS_fsm_state23;
wire   [6:0] add_ln145_fu_391_p2;
reg   [6:0] add_ln145_reg_777;
wire    ap_CS_fsm_state24;
reg   [31:0] tmp_2_reg_782;
wire    ap_CS_fsm_state25;
wire   [31:0] grp_hls_get_coordinate_fu_252_ap_return;
reg   [31:0] tmp_3_reg_787;
wire    ap_CS_fsm_state27;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_ap_done;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_ap_idle;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_ap_ready;
wire   [6:0] grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address0;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce0;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_we0;
wire   [7:0] grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_d0;
wire   [6:0] grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address1;
wire    grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce1;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_idle;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_ready;
wire   [6:0] grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_address0;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_ce0;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_done;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_idle;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_ready;
wire   [6:0] grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_address0;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_ce0;
wire   [6:0] grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_address0;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_ce0;
wire    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_we0;
wire   [7:0] grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_d0;
wire    grp_hls_get_field_from_nmea_fu_234_ap_start;
wire    grp_hls_get_field_from_nmea_fu_234_ap_done;
wire    grp_hls_get_field_from_nmea_fu_234_ap_idle;
wire    grp_hls_get_field_from_nmea_fu_234_ap_ready;
reg   [3:0] grp_hls_get_field_from_nmea_fu_234_fieldnum;
wire   [6:0] grp_hls_get_field_from_nmea_fu_234_stored_msg_address0;
wire    grp_hls_get_field_from_nmea_fu_234_stored_msg_ce0;
wire    grp_hls_atoi_w_len_fu_243_ap_start;
wire    grp_hls_atoi_w_len_fu_243_ap_done;
wire    grp_hls_atoi_w_len_fu_243_ap_idle;
wire    grp_hls_atoi_w_len_fu_243_ap_ready;
reg   [6:0] grp_hls_atoi_w_len_fu_243_s;
wire   [6:0] grp_hls_atoi_w_len_fu_243_stored_msg_address0;
wire    grp_hls_atoi_w_len_fu_243_stored_msg_ce0;
wire    grp_hls_get_coordinate_fu_252_ap_start;
wire    grp_hls_get_coordinate_fu_252_ap_done;
wire    grp_hls_get_coordinate_fu_252_ap_idle;
wire    grp_hls_get_coordinate_fu_252_ap_ready;
wire   [6:0] grp_hls_get_coordinate_fu_252_stored_msg_address0;
wire    grp_hls_get_coordinate_fu_252_stored_msg_ce0;
wire   [31:0] grp_hls_get_coordinate_fu_252_grp_fu_792_p_din0;
wire   [31:0] grp_hls_get_coordinate_fu_252_grp_fu_792_p_din1;
wire   [1:0] grp_hls_get_coordinate_fu_252_grp_fu_792_p_opcode;
wire    grp_hls_get_coordinate_fu_252_grp_fu_792_p_ce;
wire   [31:0] grp_hls_get_coordinate_fu_252_grp_fu_796_p_din0;
wire   [31:0] grp_hls_get_coordinate_fu_252_grp_fu_796_p_din1;
wire    grp_hls_get_coordinate_fu_252_grp_fu_796_p_ce;
wire   [31:0] grp_hls_get_coordinate_fu_252_grp_fu_800_p_din0;
wire    grp_hls_get_coordinate_fu_252_grp_fu_800_p_ce;
wire    grp_hls_get_coordinate_1_fu_258_ap_start;
wire    grp_hls_get_coordinate_1_fu_258_ap_done;
wire    grp_hls_get_coordinate_1_fu_258_ap_idle;
wire    grp_hls_get_coordinate_1_fu_258_ap_ready;
wire   [6:0] grp_hls_get_coordinate_1_fu_258_stored_msg_address0;
wire    grp_hls_get_coordinate_1_fu_258_stored_msg_ce0;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_ap_return;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din0;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din1;
wire   [1:0] grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_opcode;
wire    grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_ce;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din0;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din1;
wire    grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_ce;
wire   [31:0] grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_din0;
wire    grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_ce;
reg   [7:0] ap_phi_mux_empty_phi_fu_187_p4;
reg   [7:0] empty_reg_184;
wire   [319:0] or_ln_fu_653_p11;
reg   [319:0] ap_phi_mux_gd_new_0_phi_fu_198_p8;
reg   [319:0] gd_new_0_reg_194;
wire    ap_CS_fsm_state29;
reg    ap_predicate_op96_call_state29;
reg    ap_block_state29_on_subcall_done;
reg    grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg;
reg    grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_hls_get_field_from_nmea_fu_234_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
reg    grp_hls_atoi_w_len_fu_243_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state20;
reg    grp_hls_get_coordinate_fu_252_ap_start_reg;
wire    ap_CS_fsm_state26;
reg    grp_hls_get_coordinate_1_fu_258_ap_start_reg;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state3;
wire  signed [25:0] mul_ln40_fu_264_p0;
wire  signed [31:0] era_fu_507_p3;
wire   [18:0] mul_ln40_fu_264_p1;
wire   [31:0] mul_ln38_1_fu_269_p0;
wire   [33:0] mul_ln38_1_fu_269_p1;
wire   [31:0] mul_ln39_1_fu_274_p0;
wire   [33:0] mul_ln39_1_fu_274_p1;
wire  signed [31:0] mul_ln38_fu_279_p0;
wire   [8:0] mul_ln38_fu_279_p1;
wire  signed [31:0] yoe_fu_522_p2;
wire   [9:0] mul_ln39_fu_284_p1;
wire  signed [31:0] mul_ln151_fu_289_p0;
wire   [17:0] mul_ln151_fu_289_p1;
wire   [33:0] mul_ln36_fu_294_p1;
wire   [29:0] shl_ln_fu_323_p3;
wire   [29:0] shl_ln146_1_fu_330_p3;
wire   [29:0] sub_ln146_fu_337_p2;
wire   [29:0] trunc_ln142_fu_319_p1;
wire   [31:0] shl_ln146_2_fu_359_p3;
wire   [31:0] shl_ln146_3_fu_366_p3;
wire   [31:0] sub_ln146_1_fu_373_p2;
wire   [0:0] icmp_ln35_fu_409_p2;
wire   [31:0] y_fu_397_p2;
wire   [31:0] zext_ln35_fu_414_p1;
wire   [31:0] sub_ln35_fu_418_p2;
wire   [0:0] tmp_5_fu_424_p3;
wire   [31:0] add_ln36_fu_432_p2;
wire  signed [31:0] select_ln36_fu_438_p3;
wire   [64:0] mul_ln36_fu_294_p2;
wire   [64:0] sub_ln36_fu_451_p2;
wire  signed [23:0] tmp_8_fu_475_p4;
wire   [0:0] tmp_6_fu_457_p3;
wire   [23:0] tmp_7_fu_465_p4;
wire   [23:0] select_ln36_2_fu_489_p3;
wire  signed [31:0] sext_ln36_2_fu_497_p1;
wire   [31:0] sub_ln36_1_fu_501_p2;
wire  signed [31:0] sext_ln36_1_fu_485_p1;
wire  signed [25:0] mul_ln37_fu_516_p0;
wire  signed [9:0] mul_ln37_fu_516_p1;
wire   [31:0] mul_ln37_fu_516_p2;
wire   [0:0] icmp_ln38_fu_529_p2;
wire   [31:0] select_ln38_fu_534_p3;
wire   [31:0] mul_ln38_fu_279_p2;
wire   [31:0] add_ln38_1_fu_548_p2;
wire   [64:0] mul_ln38_1_fu_269_p2;
wire   [29:0] tmp_10_fu_559_p4;
wire   [29:0] lshr_ln_fu_573_p4;
wire   [64:0] mul_ln39_1_fu_274_p2;
wire   [25:0] tmp_11_fu_592_p4;
wire   [31:0] zext_ln38_1_fu_569_p1;
wire   [31:0] mul_ln40_fu_264_p2;
wire   [31:0] add_ln39_2_fu_611_p2;
wire   [31:0] add_ln39_1_fu_606_p2;
wire   [31:0] add_ln39_fu_617_p2;
wire   [31:0] zext_ln39_2_fu_602_p1;
wire   [31:0] zext_ln39_fu_583_p1;
wire   [31:0] mul_ln39_fu_284_p2;
wire   [31:0] add_ln40_1_fu_629_p2;
wire   [31:0] sub_ln39_fu_623_p2;
wire   [31:0] mul_ln151_fu_289_p2;
wire   [31:0] add_ln151_fu_642_p2;
wire   [31:0] add_ln151_1_fu_648_p2;
wire   [31:0] bitcast_ln149_fu_405_p1;
wire   [31:0] bitcast_ln148_fu_402_p1;
wire   [31:0] grp_fu_792_p2;
reg   [31:0] grp_fu_792_p0;
reg   [31:0] grp_fu_792_p1;
reg    grp_fu_792_ce;
wire   [31:0] grp_fu_796_p2;
reg   [31:0] grp_fu_796_p0;
reg   [31:0] grp_fu_796_p1;
reg    grp_fu_796_ce;
wire   [31:0] grp_fu_800_p1;
reg   [31:0] grp_fu_800_p0;
reg    grp_fu_800_ce;
reg   [28:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    regslice_both_msg_U_apdone_blk;
wire   [7:0] msg_TDATA_int_regslice;
wire    msg_TVALID_int_regslice;
reg    msg_TREADY_int_regslice;
wire    regslice_both_msg_U_ack_in;
wire   [64:0] mul_ln38_1_fu_269_p00;
wire   [64:0] mul_ln39_1_fu_274_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 29'd1;
#0 grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg = 1'b0;
#0 grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg = 1'b0;
#0 grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg = 1'b0;
#0 grp_hls_get_field_from_nmea_fu_234_ap_start_reg = 1'b0;
#0 grp_hls_atoi_w_len_fu_243_ap_start_reg = 1'b0;
#0 grp_hls_get_coordinate_fu_252_ap_start_reg = 1'b0;
#0 grp_hls_get_coordinate_1_fu_258_ap_start_reg = 1'b0;
end

gps_translation_msg_shift_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 82 ),
    .AddressWidth( 7 ))
msg_shift_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(msg_shift_address0),
    .ce0(msg_shift_ce0),
    .we0(msg_shift_we0),
    .d0(msg_shift_d0),
    .q0(msg_shift_q0),
    .address1(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address1),
    .ce1(msg_shift_ce1),
    .q1(msg_shift_q1)
);

gps_translation_stored_msg_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 82 ),
    .AddressWidth( 7 ))
stored_msg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(stored_msg_address0),
    .ce0(stored_msg_ce0),
    .we0(stored_msg_we0),
    .d0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_d0),
    .q0(stored_msg_q0)
);

gps_translation_gps_translation_Pipeline_shift_loop grp_gps_translation_Pipeline_shift_loop_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start),
    .ap_done(grp_gps_translation_Pipeline_shift_loop_fu_212_ap_done),
    .ap_idle(grp_gps_translation_Pipeline_shift_loop_fu_212_ap_idle),
    .ap_ready(grp_gps_translation_Pipeline_shift_loop_fu_212_ap_ready),
    .msg_shift_address0(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address0),
    .msg_shift_ce0(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce0),
    .msg_shift_we0(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_we0),
    .msg_shift_d0(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_d0),
    .msg_shift_address1(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address1),
    .msg_shift_ce1(grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce1),
    .msg_shift_q1(msg_shift_q1)
);

gps_translation_gps_translation_Pipeline_VITIS_LOOP_23_1 grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start),
    .ap_done(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done),
    .ap_idle(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_idle),
    .ap_ready(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_ready),
    .msg_shift_address0(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_address0),
    .msg_shift_ce0(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_ce0),
    .msg_shift_q0(msg_shift_q0),
    .ap_return(grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return)
);

gps_translation_gps_translation_Pipeline_VITIS_LOOP_132_1 grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start),
    .ap_done(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_done),
    .ap_idle(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_idle),
    .ap_ready(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_ready),
    .msg_shift_address0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_address0),
    .msg_shift_ce0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_ce0),
    .msg_shift_q0(msg_shift_q0),
    .stored_msg_address0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_address0),
    .stored_msg_ce0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_ce0),
    .stored_msg_we0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_we0),
    .stored_msg_d0(grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_d0)
);

gps_translation_hls_get_field_from_nmea grp_hls_get_field_from_nmea_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_get_field_from_nmea_fu_234_ap_start),
    .ap_done(grp_hls_get_field_from_nmea_fu_234_ap_done),
    .ap_idle(grp_hls_get_field_from_nmea_fu_234_ap_idle),
    .ap_ready(grp_hls_get_field_from_nmea_fu_234_ap_ready),
    .fieldnum(grp_hls_get_field_from_nmea_fu_234_fieldnum),
    .stored_msg_address0(grp_hls_get_field_from_nmea_fu_234_stored_msg_address0),
    .stored_msg_ce0(grp_hls_get_field_from_nmea_fu_234_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_get_field_from_nmea_fu_234_ap_return)
);

gps_translation_hls_atoi_w_len grp_hls_atoi_w_len_fu_243(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_atoi_w_len_fu_243_ap_start),
    .ap_done(grp_hls_atoi_w_len_fu_243_ap_done),
    .ap_idle(grp_hls_atoi_w_len_fu_243_ap_idle),
    .ap_ready(grp_hls_atoi_w_len_fu_243_ap_ready),
    .s(grp_hls_atoi_w_len_fu_243_s),
    .n(3'd2),
    .stored_msg_address0(grp_hls_atoi_w_len_fu_243_stored_msg_address0),
    .stored_msg_ce0(grp_hls_atoi_w_len_fu_243_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_atoi_w_len_fu_243_ap_return)
);

gps_translation_hls_get_coordinate grp_hls_get_coordinate_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_get_coordinate_fu_252_ap_start),
    .ap_done(grp_hls_get_coordinate_fu_252_ap_done),
    .ap_idle(grp_hls_get_coordinate_fu_252_ap_idle),
    .ap_ready(grp_hls_get_coordinate_fu_252_ap_ready),
    .stored_msg_address0(grp_hls_get_coordinate_fu_252_stored_msg_address0),
    .stored_msg_ce0(grp_hls_get_coordinate_fu_252_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_get_coordinate_fu_252_ap_return),
    .grp_fu_792_p_din0(grp_hls_get_coordinate_fu_252_grp_fu_792_p_din0),
    .grp_fu_792_p_din1(grp_hls_get_coordinate_fu_252_grp_fu_792_p_din1),
    .grp_fu_792_p_opcode(grp_hls_get_coordinate_fu_252_grp_fu_792_p_opcode),
    .grp_fu_792_p_dout0(grp_fu_792_p2),
    .grp_fu_792_p_ce(grp_hls_get_coordinate_fu_252_grp_fu_792_p_ce),
    .grp_fu_796_p_din0(grp_hls_get_coordinate_fu_252_grp_fu_796_p_din0),
    .grp_fu_796_p_din1(grp_hls_get_coordinate_fu_252_grp_fu_796_p_din1),
    .grp_fu_796_p_dout0(grp_fu_796_p2),
    .grp_fu_796_p_ce(grp_hls_get_coordinate_fu_252_grp_fu_796_p_ce),
    .grp_fu_800_p_din0(grp_hls_get_coordinate_fu_252_grp_fu_800_p_din0),
    .grp_fu_800_p_dout0(grp_fu_800_p1),
    .grp_fu_800_p_ce(grp_hls_get_coordinate_fu_252_grp_fu_800_p_ce)
);

gps_translation_hls_get_coordinate_1 grp_hls_get_coordinate_1_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_get_coordinate_1_fu_258_ap_start),
    .ap_done(grp_hls_get_coordinate_1_fu_258_ap_done),
    .ap_idle(grp_hls_get_coordinate_1_fu_258_ap_idle),
    .ap_ready(grp_hls_get_coordinate_1_fu_258_ap_ready),
    .stored_msg_address0(grp_hls_get_coordinate_1_fu_258_stored_msg_address0),
    .stored_msg_ce0(grp_hls_get_coordinate_1_fu_258_stored_msg_ce0),
    .stored_msg_q0(stored_msg_q0),
    .ap_return(grp_hls_get_coordinate_1_fu_258_ap_return),
    .grp_fu_792_p_din0(grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din0),
    .grp_fu_792_p_din1(grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din1),
    .grp_fu_792_p_opcode(grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_opcode),
    .grp_fu_792_p_dout0(grp_fu_792_p2),
    .grp_fu_792_p_ce(grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_ce),
    .grp_fu_796_p_din0(grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din0),
    .grp_fu_796_p_din1(grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din1),
    .grp_fu_796_p_dout0(grp_fu_796_p2),
    .grp_fu_796_p_ce(grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_ce),
    .grp_fu_800_p_din0(grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_din0),
    .grp_fu_800_p_dout0(grp_fu_800_p1),
    .grp_fu_800_p_ce(grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_ce)
);

gps_translation_mul_26s_19ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 19 ),
    .dout_WIDTH( 32 ))
mul_26s_19ns_32_1_1_U30(
    .din0(mul_ln40_fu_264_p0),
    .din1(mul_ln40_fu_264_p1),
    .dout(mul_ln40_fu_264_p2)
);

gps_translation_mul_32ns_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_1_1_U31(
    .din0(mul_ln38_1_fu_269_p0),
    .din1(mul_ln38_1_fu_269_p1),
    .dout(mul_ln38_1_fu_269_p2)
);

gps_translation_mul_32ns_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_1_1_U32(
    .din0(mul_ln39_1_fu_274_p0),
    .din1(mul_ln39_1_fu_274_p1),
    .dout(mul_ln39_1_fu_274_p2)
);

gps_translation_mul_32s_9ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 32 ))
mul_32s_9ns_32_1_1_U33(
    .din0(mul_ln38_fu_279_p0),
    .din1(mul_ln38_fu_279_p1),
    .dout(mul_ln38_fu_279_p2)
);

gps_translation_mul_32s_10ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 32 ))
mul_32s_10ns_32_1_1_U34(
    .din0(yoe_fu_522_p2),
    .din1(mul_ln39_fu_284_p1),
    .dout(mul_ln39_fu_284_p2)
);

gps_translation_mul_32s_18ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 32 ))
mul_32s_18ns_32_1_1_U35(
    .din0(mul_ln151_fu_289_p0),
    .din1(mul_ln151_fu_289_p1),
    .dout(mul_ln151_fu_289_p2)
);

gps_translation_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U36(
    .din0(select_ln36_fu_438_p3),
    .din1(mul_ln36_fu_294_p1),
    .dout(mul_ln36_fu_294_p2)
);

gps_translation_mul_26s_10s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 32 ))
mul_26s_10s_32_1_1_U37(
    .din0(mul_ln37_fu_516_p0),
    .din1(mul_ln37_fu_516_p1),
    .dout(mul_ln37_fu_516_p2)
);

gps_translation_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_792_p0),
    .din1(grp_fu_792_p1),
    .ce(grp_fu_792_ce),
    .dout(grp_fu_792_p2)
);

gps_translation_fdiv_32ns_32ns_32_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_3_no_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_796_p0),
    .din1(grp_fu_796_p1),
    .ce(grp_fu_796_ce),
    .dout(grp_fu_796_p2)
);

gps_translation_sitofp_32ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_2_no_dsp_1_U40(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_800_p0),
    .ce(grp_fu_800_ce),
    .dout(grp_fu_800_p1)
);

gps_translation_regslice_both #(
    .DataWidth( 8 ))
regslice_both_msg_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(msg_TDATA),
    .vld_in(msg_TVALID),
    .ack_in(regslice_both_msg_U_ack_in),
    .data_out(msg_TDATA_int_regslice),
    .vld_out(msg_TVALID_int_regslice),
    .ack_out(msg_TREADY_int_regslice),
    .apdone_blk(regslice_both_msg_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg <= 1'b1;
        end else if ((grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_ready == 1'b1)) begin
            grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_ready == 1'b1)) begin
            grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_gps_translation_Pipeline_shift_loop_fu_212_ap_ready == 1'b1)) begin
            grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_atoi_w_len_fu_243_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16))) begin
            grp_hls_atoi_w_len_fu_243_ap_start_reg <= 1'b1;
        end else if ((grp_hls_atoi_w_len_fu_243_ap_ready == 1'b1)) begin
            grp_hls_atoi_w_len_fu_243_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_get_coordinate_1_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state28)) begin
            grp_hls_get_coordinate_1_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_hls_get_coordinate_1_fu_258_ap_ready == 1'b1)) begin
            grp_hls_get_coordinate_1_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_get_coordinate_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_hls_get_coordinate_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_hls_get_coordinate_fu_252_ap_ready == 1'b1)) begin
            grp_hls_get_coordinate_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_get_field_from_nmea_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10))) begin
            grp_hls_get_field_from_nmea_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_hls_get_field_from_nmea_fu_234_ap_ready == 1'b1)) begin
            grp_hls_get_field_from_nmea_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((msg_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_reg_184 <= msg_TDATA_int_regslice;
    end else if (((tmp_reg_676 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_reg_184 <= msg_shift_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((pps_read_read_fu_142_p2 == 1'd0) & (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7) & (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return == 1'd1)) | ((grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7) & (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return == 1'd0)) | ((icmp_ln127_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        gd_new_0_reg_194 <= 320'd0;
    end else if (((icmp_ln127_reg_680 == 1'd1) & (pps == 1'd1) & (1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29) & (targetBlock_reg_689 == 1'd1))) begin
        gd_new_0_reg_194 <= or_ln_fu_653_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln141_reg_722 <= add_ln141_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        add_ln142_reg_742 <= add_ln142_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln144_reg_764 <= add_ln144_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln145_reg_777 <= add_ln145_fu_391_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln146_1_reg_752 <= add_ln146_1_fu_379_p2;
        tmp_1_reg_747 <= grp_hls_atoi_w_len_fu_243_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln146_reg_732 <= add_ln146_fu_343_p2;
        tmp_s_reg_727 <= grp_hls_atoi_w_len_fu_243_ap_return;
        trunc_ln146_2_reg_737 <= trunc_ln146_2_fu_349_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        d_reg_758 <= grp_hls_atoi_w_len_fu_243_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        date_str_reg_700 <= grp_hls_get_field_from_nmea_fu_234_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln127_reg_680 <= icmp_ln127_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        m_reg_769 <= grp_hls_atoi_w_len_fu_243_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        targetBlock_reg_689 <= grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp_2_reg_782 <= grp_hls_atoi_w_len_fu_243_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        tmp_3_reg_787 <= grp_hls_get_coordinate_fu_252_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_9_reg_707 <= grp_hls_atoi_w_len_fu_243_ap_return;
        trunc_ln146_1_reg_717 <= trunc_ln146_1_fu_309_p1;
        trunc_ln146_reg_712 <= trunc_ln146_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_676 <= tmp_nbreadreq_fu_148_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ts_str_reg_693 <= grp_hls_get_field_from_nmea_fu_234_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_field_from_nmea_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_field_from_nmea_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_atoi_w_len_fu_243_ap_done == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_get_coordinate_fu_252_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state29_on_subcall_done)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_gps_translation_Pipeline_shift_loop_fu_212_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((msg_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_676 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_empty_phi_fu_187_p4 = msg_shift_q0;
    end else begin
        ap_phi_mux_empty_phi_fu_187_p4 = empty_reg_184;
    end
end

always @ (*) begin
    if (((icmp_ln127_reg_680 == 1'd1) & (pps == 1'd1) & (1'b1 == ap_CS_fsm_state29) & (targetBlock_reg_689 == 1'd1))) begin
        ap_phi_mux_gd_new_0_phi_fu_198_p8 = or_ln_fu_653_p11;
    end else begin
        ap_phi_mux_gd_new_0_phi_fu_198_p8 = gd_new_0_reg_194;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln127_reg_680 == 1'd1) & (pps == 1'd1) & (1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29) & (targetBlock_reg_689 == 1'd1))) begin
        data_valid_ap_vld = 1'b1;
    end else begin
        data_valid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29))) begin
        gd_ap_vld = 1'b1;
    end else begin
        gd_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_792_ce = grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_792_ce = grp_hls_get_coordinate_fu_252_grp_fu_792_p_ce;
    end else begin
        grp_fu_792_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_792_p0 = grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_792_p0 = grp_hls_get_coordinate_fu_252_grp_fu_792_p_din0;
    end else begin
        grp_fu_792_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_792_p1 = grp_hls_get_coordinate_1_fu_258_grp_fu_792_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_792_p1 = grp_hls_get_coordinate_fu_252_grp_fu_792_p_din1;
    end else begin
        grp_fu_792_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_796_ce = grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_796_ce = grp_hls_get_coordinate_fu_252_grp_fu_796_p_ce;
    end else begin
        grp_fu_796_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_796_p0 = grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_796_p0 = grp_hls_get_coordinate_fu_252_grp_fu_796_p_din0;
    end else begin
        grp_fu_796_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_796_p1 = grp_hls_get_coordinate_1_fu_258_grp_fu_796_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_796_p1 = grp_hls_get_coordinate_fu_252_grp_fu_796_p_din1;
    end else begin
        grp_fu_796_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_800_ce = grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_800_ce = grp_hls_get_coordinate_fu_252_grp_fu_800_p_ce;
    end else begin
        grp_fu_800_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_800_p0 = grp_hls_get_coordinate_1_fu_258_grp_fu_800_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_800_p0 = grp_hls_get_coordinate_fu_252_grp_fu_800_p_din0;
    end else begin
        grp_fu_800_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_hls_atoi_w_len_fu_243_s = add_ln145_reg_777;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_hls_atoi_w_len_fu_243_s = add_ln144_reg_764;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_hls_atoi_w_len_fu_243_s = date_str_reg_700;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_hls_atoi_w_len_fu_243_s = add_ln142_reg_742;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_hls_atoi_w_len_fu_243_s = add_ln141_reg_722;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_hls_atoi_w_len_fu_243_s = ts_str_reg_693;
    end else begin
        grp_hls_atoi_w_len_fu_243_s = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_hls_get_field_from_nmea_fu_234_fieldnum = 4'd9;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_hls_get_field_from_nmea_fu_234_fieldnum = 4'd1;
    end else begin
        grp_hls_get_field_from_nmea_fu_234_fieldnum = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        msg_TDATA_blk_n = msg_TVALID_int_regslice;
    end else begin
        msg_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((msg_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        msg_TREADY_int_regslice = 1'b1;
    end else begin
        msg_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        msg_shift_address0 = 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        msg_shift_address0 = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        msg_shift_address0 = grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        msg_shift_address0 = grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_address0;
    end else begin
        msg_shift_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((msg_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        msg_shift_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        msg_shift_ce0 = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_msg_shift_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        msg_shift_ce0 = grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_msg_shift_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        msg_shift_ce0 = grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce0;
    end else begin
        msg_shift_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        msg_shift_ce1 = grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_ce1;
    end else begin
        msg_shift_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        msg_shift_d0 = msg_TDATA_int_regslice;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        msg_shift_d0 = grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_d0;
    end else begin
        msg_shift_d0 = 'bx;
    end
end

always @ (*) begin
    if (((msg_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        msg_shift_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        msg_shift_we0 = grp_gps_translation_Pipeline_shift_loop_fu_212_msg_shift_we0;
    end else begin
        msg_shift_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op96_call_state29 == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        stored_msg_address0 = grp_hls_get_coordinate_1_fu_258_stored_msg_address0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        stored_msg_address0 = grp_hls_get_coordinate_fu_252_stored_msg_address0;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15))) begin
        stored_msg_address0 = grp_hls_atoi_w_len_fu_243_stored_msg_address0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11))) begin
        stored_msg_address0 = grp_hls_get_field_from_nmea_fu_234_stored_msg_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        stored_msg_address0 = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_address0;
    end else begin
        stored_msg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op96_call_state29 == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        stored_msg_ce0 = grp_hls_get_coordinate_1_fu_258_stored_msg_ce0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        stored_msg_ce0 = grp_hls_get_coordinate_fu_252_stored_msg_ce0;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15))) begin
        stored_msg_ce0 = grp_hls_atoi_w_len_fu_243_stored_msg_ce0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11))) begin
        stored_msg_ce0 = grp_hls_get_field_from_nmea_fu_234_stored_msg_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        stored_msg_ce0 = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_ce0;
    end else begin
        stored_msg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        stored_msg_we0 = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_stored_msg_we0;
    end else begin
        stored_msg_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_nbreadreq_fu_148_p3 == 1'd1) & (grp_gps_translation_Pipeline_shift_loop_fu_212_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((tmp_nbreadreq_fu_148_p3 == 1'd0) & (grp_gps_translation_Pipeline_shift_loop_fu_212_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln127_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((msg_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((pps == 1'd1) & (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7) & (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7) & ((pps_read_read_fu_142_p2 == 1'd0) | (grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_return == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_hls_get_field_from_nmea_fu_234_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_hls_get_field_from_nmea_fu_234_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_hls_atoi_w_len_fu_243_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_hls_get_coordinate_fu_252_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((1'b0 == ap_block_state29_on_subcall_done) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln141_fu_313_p2 = (ts_str_reg_693 + 7'd2);

assign add_ln142_fu_353_p2 = (ts_str_reg_693 + 7'd4);

assign add_ln144_fu_385_p2 = (date_str_reg_700 + 7'd2);

assign add_ln145_fu_391_p2 = (date_str_reg_700 + 7'd4);

assign add_ln146_1_fu_379_p2 = (sub_ln146_1_fu_373_p2 + grp_hls_atoi_w_len_fu_243_ap_return);

assign add_ln146_fu_343_p2 = (sub_ln146_fu_337_p2 + trunc_ln142_fu_319_p1);

assign add_ln151_1_fu_648_p2 = (add_ln151_fu_642_p2 + add_ln146_1_reg_752);

assign add_ln151_fu_642_p2 = ($signed(mul_ln151_fu_289_p2) + $signed(32'd2262474240));

assign add_ln36_fu_432_p2 = ($signed(sub_ln35_fu_418_p2) + $signed(32'd4294966897));

assign add_ln38_1_fu_548_p2 = (mul_ln38_fu_279_p2 + 32'd2);

assign add_ln39_1_fu_606_p2 = (d_reg_758 + zext_ln38_1_fu_569_p1);

assign add_ln39_2_fu_611_p2 = ($signed(mul_ln40_fu_264_p2) + $signed(32'd4294967295));

assign add_ln39_fu_617_p2 = (add_ln39_2_fu_611_p2 + add_ln39_1_fu_606_p2);

assign add_ln40_1_fu_629_p2 = (zext_ln39_fu_583_p1 + mul_ln39_fu_284_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state29_on_subcall_done = ((ap_predicate_op96_call_state29 == 1'b1) & (grp_hls_get_coordinate_1_fu_258_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op96_call_state29 = ((icmp_ln127_reg_680 == 1'd1) & (pps == 1'd1) & (targetBlock_reg_689 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln148_fu_402_p1 = tmp_3_reg_787;

assign bitcast_ln149_fu_405_p1 = grp_hls_get_coordinate_1_fu_258_ap_return;

assign data_valid = 1'd1;

assign era_fu_507_p3 = ((tmp_6_fu_457_p3[0:0] == 1'b1) ? sub_ln36_1_fu_501_p2 : sext_ln36_1_fu_485_p1);

assign gd = ap_phi_mux_gd_new_0_phi_fu_198_p8;

assign grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start = grp_gps_translation_Pipeline_VITIS_LOOP_132_1_fu_226_ap_start_reg;

assign grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start = grp_gps_translation_Pipeline_VITIS_LOOP_23_1_fu_218_ap_start_reg;

assign grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start = grp_gps_translation_Pipeline_shift_loop_fu_212_ap_start_reg;

assign grp_hls_atoi_w_len_fu_243_ap_start = grp_hls_atoi_w_len_fu_243_ap_start_reg;

assign grp_hls_get_coordinate_1_fu_258_ap_start = grp_hls_get_coordinate_1_fu_258_ap_start_reg;

assign grp_hls_get_coordinate_fu_252_ap_start = grp_hls_get_coordinate_fu_252_ap_start_reg;

assign grp_hls_get_field_from_nmea_fu_234_ap_start = grp_hls_get_field_from_nmea_fu_234_ap_start_reg;

assign icmp_ln127_fu_299_p2 = ((ap_phi_mux_empty_phi_fu_187_p4 == 8'd36) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_409_p2 = ((m_reg_769 < 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_529_p2 = ((m_reg_769 > 32'd2) ? 1'b1 : 1'b0);

assign lshr_ln_fu_573_p4 = {{yoe_fu_522_p2[31:2]}};

assign msg_TREADY = regslice_both_msg_U_ack_in;

assign mul_ln151_fu_289_p0 = (add_ln40_1_fu_629_p2 + sub_ln39_fu_623_p2);

assign mul_ln151_fu_289_p1 = 32'd86400;

assign mul_ln36_fu_294_p1 = 65'd5497558139;

assign mul_ln37_fu_516_p0 = era_fu_507_p3;

assign mul_ln37_fu_516_p1 = 32'd4294966896;

assign mul_ln38_1_fu_269_p0 = mul_ln38_1_fu_269_p00;

assign mul_ln38_1_fu_269_p00 = add_ln38_1_fu_548_p2;

assign mul_ln38_1_fu_269_p1 = 65'd6871947674;

assign mul_ln38_fu_279_p0 = (select_ln38_fu_534_p3 + m_reg_769);

assign mul_ln38_fu_279_p1 = 32'd153;

assign mul_ln39_1_fu_274_p0 = mul_ln39_1_fu_274_p00;

assign mul_ln39_1_fu_274_p00 = $unsigned(yoe_fu_522_p2);

assign mul_ln39_1_fu_274_p1 = 65'd5497558139;

assign mul_ln39_fu_284_p1 = 32'd365;

assign mul_ln40_fu_264_p0 = era_fu_507_p3;

assign mul_ln40_fu_264_p1 = 32'd146097;

assign or_ln_fu_653_p11 = {{{{{{{{{{add_ln151_1_fu_648_p2}, {add_ln146_1_reg_752}}, {bitcast_ln149_fu_405_p1}}, {bitcast_ln148_fu_402_p1}}, {y_fu_397_p2}}, {m_reg_769}}, {d_reg_758}}, {tmp_1_reg_747}}, {tmp_s_reg_727}}, {tmp_9_reg_707}};

assign pps_read_read_fu_142_p2 = pps;

assign select_ln36_2_fu_489_p3 = ((tmp_6_fu_457_p3[0:0] == 1'b1) ? tmp_7_fu_465_p4 : tmp_8_fu_475_p4);

assign select_ln36_fu_438_p3 = ((tmp_5_fu_424_p3[0:0] == 1'b1) ? add_ln36_fu_432_p2 : sub_ln35_fu_418_p2);

assign select_ln38_fu_534_p3 = ((icmp_ln38_fu_529_p2[0:0] == 1'b1) ? 32'd4294967293 : 32'd9);

assign sext_ln36_1_fu_485_p1 = tmp_8_fu_475_p4;

assign sext_ln36_2_fu_497_p1 = $signed(select_ln36_2_fu_489_p3);

assign shl_ln146_1_fu_330_p3 = {{trunc_ln146_1_reg_717}, {2'd0}};

assign shl_ln146_2_fu_359_p3 = {{trunc_ln146_2_reg_737}, {6'd0}};

assign shl_ln146_3_fu_366_p3 = {{add_ln146_reg_732}, {2'd0}};

assign shl_ln_fu_323_p3 = {{trunc_ln146_reg_712}, {6'd0}};

assign sub_ln146_1_fu_373_p2 = (shl_ln146_2_fu_359_p3 - shl_ln146_3_fu_366_p3);

assign sub_ln146_fu_337_p2 = (shl_ln_fu_323_p3 - shl_ln146_1_fu_330_p3);

assign sub_ln35_fu_418_p2 = (y_fu_397_p2 - zext_ln35_fu_414_p1);

assign sub_ln36_1_fu_501_p2 = ($signed(32'd0) - $signed(sext_ln36_2_fu_497_p1));

assign sub_ln36_fu_451_p2 = (65'd0 - mul_ln36_fu_294_p2);

assign sub_ln39_fu_623_p2 = (add_ln39_fu_617_p2 - zext_ln39_2_fu_602_p1);

assign tmp_10_fu_559_p4 = {{mul_ln38_1_fu_269_p2[64:35]}};

assign tmp_11_fu_592_p4 = {{mul_ln39_1_fu_274_p2[64:39]}};

assign tmp_5_fu_424_p3 = sub_ln35_fu_418_p2[32'd31];

assign tmp_6_fu_457_p3 = select_ln36_fu_438_p3[32'd31];

assign tmp_7_fu_465_p4 = {{sub_ln36_fu_451_p2[64:41]}};

assign tmp_8_fu_475_p4 = {{mul_ln36_fu_294_p2[64:41]}};

assign tmp_nbreadreq_fu_148_p3 = msg_TVALID_int_regslice;

assign trunc_ln142_fu_319_p1 = grp_hls_atoi_w_len_fu_243_ap_return[29:0];

assign trunc_ln146_1_fu_309_p1 = grp_hls_atoi_w_len_fu_243_ap_return[27:0];

assign trunc_ln146_2_fu_349_p1 = add_ln146_fu_343_p2[25:0];

assign trunc_ln146_fu_305_p1 = grp_hls_atoi_w_len_fu_243_ap_return[23:0];

assign y_fu_397_p2 = (tmp_2_reg_782 + 32'd2000);

assign yoe_fu_522_p2 = (mul_ln37_fu_516_p2 + sub_ln35_fu_418_p2);

assign zext_ln35_fu_414_p1 = icmp_ln35_fu_409_p2;

assign zext_ln38_1_fu_569_p1 = tmp_10_fu_559_p4;

assign zext_ln39_2_fu_602_p1 = tmp_11_fu_592_p4;

assign zext_ln39_fu_583_p1 = lshr_ln_fu_573_p4;

endmodule //gps_translation
